[project]
authors = ["Mehmet Efe Ak√ßa <efeakca@gmail.com>"]
channels = ["conda-forge"]
description = "star-go model"
name = "stargo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<4"
pytorch = ">=2.5.1,<3"
pytoml = ">=0.1.21,<0.2"
pytest = ">=8.3.4,<9"
toml = ">=0.10.2,<0.11"
lightning = ">=2.4.0,<3"
tensorboard = ">=2.18.0,<3"
plotly = ">=5.24.1,<6"
goatools = ">=1.4.12,<2"
ipykernel = ">=6.29.5,<7"
h5py = ">=3.12.1,<4"
transformers = ">=4.47.0,<5"
click = ">=8.1.7,<9"
wandb = ">=0.19.0,<0.20"
line_profiler = ">=4.1.3,<5"
scikit-learn = ">=1.6.0,<2"
plotly_express = ">=0.4.1,<0.5"
pydantic = ">=2.10.4,<3"
loguru = ">=0.7.2,<0.8"
einops = ">=0.8.0,<0.9"
torchinfo = ">=1.8.0,<2"
sentence-transformers = ">=3.3.1,<4"
pillow = ">=11.1.0,<12"

[pypi-dependencies]
wget = ">=3.2, <4"
py-heat-magic = ">=0.0.2, <0.0.3"
fastobo = ">=0.12.3, <0.13"
obonet = ">=1.1.0, <2"
matplotlib = ">=3.10.0, <4"
seaborn = ">=0.13.2, <0.14"
torchsummary = ">=1.5.1, <2"
pillow = "*"
